name: Solve A Riddle
description: |
  author: [Phuong Phan]()

  Here's a simple website with a simple riddle you can try to solve. Can you find the page containing the hints for the flag?

  **Connection Instructions**:

  Do the following:

  $ `ssh -L localhost:<local port>:solve-a-riddle:80 -p 56151 <username>@cs561.cs.umass.edu`

  Now you can connect to `http://localhost:<local port>` to access the challenge.

  For example, run

  $ `ssh -L localhost:8080:solve-a-riddle:80 -p 56151 user@cs561.cs.umass.edu`

  This will forward the local port 8080 on your machine to `solve-a-riddle:80` on the swarm network, where this challenge is hosted.

  Now, open the website at `http://localhost:8080` to access the challenge.

  Flag is in standard format CTF_SDaT{f0_f1_f2}. Concatenate all flags that you found into one using the underscore character `_` and wrap them inside CTF_SDaT{}.

value: 100
category: Web
flag: CTF_SDaT{N91nx_41145_JW7_4160r17HM5_J1NJ4_73MP1471N6}

# administrative
container_name: solve-a-riddle
