dev:
  postgres:
    host: !ENV ${POSTGRES_HOST:localhost}
    port: !ENV ${POSTGRES_PORT:5432}
    user: !ENV ${POSTGRES_USERNAME:postgres}
    password: !ENV ${POSTGRES_PASSWORD:postgres}
    database: !ENV ${POSTGRES_DATABASE:development}
  jwt:
    private_key: !ENV ${PRIVATE_KEY_FILE:./secret/jwt.key}
    public_key: !ENV ${PUBLIC_KEY_FILE:./secret/jwt.pub}
    access_token_expire_minutes: 30
