dev:
  version: 1
  formatters:
    standard:
      format: "%(asctime)s | %(levelname)-8s | %(name)-40s - %(message)s"

  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: standard
      stream: ext://sys.stdout

  loggers:
    uvicorn:
      level: DEBUG
      handlers: [console]

  root:
    level: DEBUG
    handlers: [console]
    propagate: false
